apiVersion: batch/v1
kind: Job
metadata:
  name: jc-centos
spec:
#  completions: 5
#  parallelism: 2
#  ActiveDeadlineSeconds: 5
  template:
    spec:
      containers:
      - name: centos-container
        image: centos:7
        command: ["bash"]
        args:
        - "-c"
        - "echo 'Hello World!'; sleep 50; echo 'Bye'"
      restartPolicy: Never
#      restartPolicy: OnFilure
#      backoffLimit: 6

